---
name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1', '3.2', '3.3']
        rails: [6-0, 6-1, 7-0, 7-1]
        exclude:
          - ruby: 2.6  # Rails 7 requires 2.7 minimum
            rails: 7-0
          - ruby: 2.6  # Rails 7.1 requires 2.7 minimum
            rails: 7-1
          - ruby: 3.1
            rails: 6-0
          - ruby: 3.1
            rails: 6-1
          - ruby: 3.2
            rails: 6-0
          - ruby: 3.2
            rails: 6-1
          - ruby: 3.3
            rails: 6-0
          - ruby: 3.3
            rails: 6-1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Bundle for Appraisal
        run: bundle

      - name: Install Appraisal dependencies
        run: bundle exec appraisal rails-${{ matrix.rails }} bundle

      - name: Run tests
        run: bundle exec appraisal rails-${{ matrix.rails }} bundle exec rspec
